name: release-please
on:
  push:
    branches:
      - main
permissions:
  # Needed for Release Please to create and update files
  contents: write
  # Needed for Release Please to create Release PRs
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
          release-type: simple
